---
- name: Prepare - Install
  hosts: all
  gather_facts: yes
  become: yes
  tasks:
    - name: "Include docker - install"
      ansible.builtin.include_role:
        name: "docker"

    - name: "Include docker_portainer - setup"
      ansible.builtin.include_role:
        name: "setup"

- name: Prepare
  hosts: all
  connection: local
  gather_facts: no
  become: no
  vars:
    ansible_connection: local
    ansible_shell_type: sh
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Include vars file
      include_vars:
        file: ./vars/main.yml

    - name: Check if windows host
      ansible.builtin.set_fact:
        is_win_host: "{{ 'win-ssh' in group_names or 'winrm' in group_names }}"

    - name: Prepare Linux Host
      when: not is_win_host
      block:
        - name: "Include use - deploy (service-1)"
          include_role:
            name: "use"
            tasks_from: deploy.yml
          vars:
            service_id: "{{ service_id_1 }}"
            docker_compose_file: "{{ docker_compose_file_1 }}"

        - name: "Include use - deploy (service-2)"
          include_role:
            name: "use"
            tasks_from: deploy.yml
          vars:
            service_id: "{{ service_id_2 }}"
            docker_compose_file: "{{ docker_compose_file_2 }}"


    - name: Prepare Windows Host
      when: is_win_host
      block:
        - name: "Include use - deploy (service-1)"
          include_role:
            name: "use"
            tasks_from: deploy.yml
          vars:
            service_id: "{{ service_id_1 }}"
            docker_compose_file: "{{ docker_compose_file_1_win }}"

#        - name: "Include use - deploy (service-2)"
#          include_role:
#            name: "use"
#            tasks_from: deploy.yml
#          vars:
#            service_id: "{{ service_id_2 }}"
#            docker_compose_file: "{{ docker_compose_file_2_win }}"