- name: Verify - docker_portainer - install
  hosts: all
  gather_facts: yes
  become: no
  tasks:
    - name: Wait for port 9000 to become open (Linux)
      when: ansible_os_family != "Windows"
      ansible.builtin.wait_for:
        port: 9000
        delay: 10
        state: absent

    - name: Wait for port 9000 to become open (Windows)
      when: ansible_os_family == "Windows"
      ansible.windows.win_wait_for:
        port: 9000
        delay: 10
        state: absent