---
- name: Install Portainer on Linux
  when: ansible_os_family != "Windows"
  block:
    - name: "Remove iptable rule for portainer ports"
      ansible.builtin.iptables:
        action: append
        chain: INPUT
        protocol: tcp
        destination_port: "{{ item }}"
        ctstate: ["NEW", "ESTABLISHED"]
        match: ["conntrack"]
        jump: "ACCEPT"
        state: absent
      with_items:
        - "8000"
        - "9000"

    - name: Set Portainer Password File Path
      ansible.builtin.set_fact:
        portainer_password_file_path: "{{ portainer_password_file_path_linux }}"
        portainer_local_endpoint_url: "{{ portainer_local_endpoint_url_linux }}"

    - name: "Delete portainer's data folder"
      ansible.builtin.file:
        path: "{{ portainer_password_file_path }}"
        state: directory
        mode: 644
        recurse: yes